#!/usr/bin/env python3
"""
OpenCode In-Place Binary Patcher

Purpose:
    Resolves the upstream API error:
    "[invalid_request_error] reasoning `encrypted_content` was not issued to this caller"
    by modifying property references inside compiled OpenCode standalone executables.

Mechanism:
    The binary executable generated by Bun bundles JavaScript source code inside an ELF
    container. During request serialization, the runtime checks the property access:
    `.reasoningEncryptedContent`.

    This patcher performs an in-place replacement of the 26-byte sequence:
        b".reasoningEncryptedContent" -> b".nonReplayEncryptedContent"

    Because the length is invariant (exactly 26 bytes including the dot), binary section
    headers, symbol offsets, and the embedded virtual filesystem (bunfs) remain strictly
    intact. At runtime, evaluating `object.nonReplayEncryptedContent` yields `undefined`,
    preventing the inclusion of expired encrypted reasoning tokens in subsequent turns.
"""

import argparse
import os
import shutil
import sys

DEFAULT_TARGET_PATHS = [
    "/data/data/com.termux/files/usr/libexec/opencode-bin",
    "/data/data/com.termux/files/usr/bin/opencode",
    os.path.expanduser("~/.local/bin/opencode"),
    "/usr/local/bin/opencode",
    "/usr/bin/opencode",
]

TARGET_PATTERN = b".reasoningEncryptedContent"
PATCH_PATTERN = b".nonReplayEncryptedContent"

assert len(TARGET_PATTERN) == len(PATCH_PATTERN) == 26, "Length constraint violation"


def resolve_binary_path(user_path=None):
    if user_path:
        expanded = os.path.abspath(os.path.expanduser(user_path))
        if os.path.isfile(expanded):
            return resolve_symlinks_and_wrappers(expanded)
        raise FileNotFoundError(f"Specified target binary not found: {expanded}")

    for candidate in DEFAULT_TARGET_PATHS:
        if os.path.isfile(candidate):
            return resolve_symlinks_and_wrappers(candidate)

    raise FileNotFoundError("Could not locate OpenCode binary in standard installation paths.")


def resolve_symlinks_and_wrappers(path):
    resolved = os.path.realpath(path)
    try:
        with open(resolved, "rb") as fp:
            header = fp.read(512)
        if header.startswith(b"#!"):
            text = header.decode("latin1", errors="replace")
            for line in text.splitlines():
                tokens = line.strip().split()
                for token in tokens:
                    candidate = os.path.realpath(token)
                    if os.path.isfile(candidate) and ("opencode" in candidate or "bin" in candidate) and candidate != resolved:
                        with open(candidate, "rb") as check_fp:
                            if check_fp.read(4) == b"\x7fELF":
                                return candidate
    except OSError:
        pass
    return resolved


def inspect_binary(target_path):
    with open(target_path, "rb") as fp:
        data = fp.read()

    unpatched_count = data.count(TARGET_PATTERN)
    patched_count = data.count(PATCH_PATTERN)
    return unpatched_count, patched_count, len(data)


def apply_patch(target_path, dry_run=False, force_backup=True):
    target_path = os.path.realpath(target_path)
    print(f"Target Binary : {target_path}")

    unpatched_count, patched_count, file_size = inspect_binary(target_path)
    print(f"File Size     : {file_size:,} bytes")
    print(f"Unpatched Occurrences : {unpatched_count}")
    print(f"Patched Occurrences   : {patched_count}")

    if unpatched_count == 0:
        if patched_count > 0:
            print("Status        : Binary has already been patched. No action required.")
            return True
        print("Status        : Target pattern not found. The binary may be an unsupported or already fixed version.")
        return False

    if dry_run:
        print("Dry run enabled. No modifications were written to disk.")
        return True

    backup_path = f"{target_path}.orig"
    if force_backup or not os.path.exists(backup_path):
        if not os.path.exists(backup_path):
            print(f"Creating backup: {backup_path}")
            shutil.copy2(target_path, backup_path)
        else:
            print(f"Preserving existing backup: {backup_path}")

    with open(target_path, "rb") as fp:
        content = fp.read()

    modified = content.replace(TARGET_PATTERN, PATCH_PATTERN)
    if len(modified) != len(content):
        raise RuntimeError("Integrity check failed: binary size deviated during patch operation.")

    with open(target_path, "wb") as fp:
        fp.write(modified)

    os.chmod(target_path, 0o755)
    print(f"Patch applied successfully across {unpatched_count} occurrence(s).")
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Patch OpenCode binary to prevent invalid reasoning encrypted_content replay."
    )
    parser.add_argument(
        "binary_path",
        nargs="?",
        default=None,
        help="Path to the target opencode executable (optional, auto-detected if omitted).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Simulate the patch process without writing changes to disk.",
    )
    parser.add_argument(
        "--no-backup",
        action="store_true",
        help="Skip creating a .orig backup file before writing modifications.",
    )

    args = parser.parse_args()

    try:
        binary_path = resolve_binary_path(args.binary_path)
        success = apply_patch(
            binary_path,
            dry_run=args.dry_run,
            force_backup=not args.no_backup,
        )
        sys.exit(0 if success else 1)
    except Exception as exc:
        print(f"Execution failed: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
